import time



class PD_Controller():
    """
    This class corresponds to the controller for the dataset
    that is generated by 
    
    """

    def __init__(self, kp, ki, kd, dt):
        self.kp = kp
        self.ki = ki 
        self.kd = kd
        self.dt = dt

    def pid_controller(self, target, current, prev_error):
        error = target - current
        derivative = (error - prev_error)/self.dt
        correction = self.kp*error + self.kd*derivative
        return correction, error